### ISSUE TITLE
i got this problem. please help me : 

### ISSUE THREAD

**Issue by hopez2024** [dreji18/Bio-Epidemiology-NER#12]
UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="simple"` instead.
  warnings.warn(
I got this problem:
Traceback (most recent call last):
  File "G:\EXPERIMENTATION\bioner.py", line 14, in <module>
    ner_prediction(corpus=doc, compute='cpu') #pass compute='gpu' if using gpu
  File "C:\Users\z\AppData\Local\Programs\Thonny\lib\site-packages\Bio_Epidemiology_NER\bio_recognizer.py", line 94, in ner_prediction
    final_df = final_df.append(disease_df) # adding the disease_df to existing
  File "C:\Users\z\AppData\Local\Programs\Thonny\lib\site-packages\pandas\core\generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

**Comment by Narendray12** [comment]
i am also getting the same error, have you got any solution?

**Comment by RageItalic** [comment]
Hi @hopez2024 @Narendray12 , was there any solution to the issue? I'm currently stuck on it as well.

**Comment by Narendray12** [comment]
@RageItalic yeah, install python 3.10 and thn download the 0.0.6 version, should work fine after that.

**Comment by Shreyjaradi** [comment]
change your pandas version to 1.5.3 and also change numpy version that is compatible to pandas version.
